//
// Created by Artur Krysiak on 2019-06-25.
//

#ifndef WEBHOOK_BUTTON_ETL_PROFILE_H
#define WEBHOOK_BUTTON_ETL_PROFILE_H

#define ETL_VERBOSE_ERRORS
#define ETL_CHECK_PUSH_POP
#define ETL_NULLPTR_INCLUDED
#define PROFILE_CPP17_GENERIC

#if !defined(ARDUINO)

#define ETL_THROW_EXCEPTIONS

#endif

#endif //WEBHOOK_BUTTON_ETL_PROFILE_H
