//
// Created by Artur Krysiak on 2019-06-25.
//

#ifndef WEBHOOK_BUTTON_ETL_PROFILE_H
#define WEBHOOK_BUTTON_ETL_PROFILE_H

#define ETL_VERBOSE_ERRORS
#define ETL_CHECK_PUSH_POP

#if defined(ARDUINO)

//#define ETL_NO_STL
#define PROFILE_CPP17_GENERIC

#else

#define ETL_THROW_EXCEPTIONS
#define ETL_NULLPTR_INCLUDED

#define PROFILE_GCC_GENERIC

#endif

#endif //WEBHOOK_BUTTON_ETL_PROFILE_H
